from .category import *
from .product_create import *
from .product_list import *
from .upload import *
from .product_retrieve import *
from .discount import *
from .comment_crud import *
from .comment import *
from .product_detail import *
from .product_image import *
